---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: avarteqgmbh/pipeline-utils

inputs:
  - name: boshrelease
  - name: version

outputs:
  - name: final-boshrelease-repository
  - name: final-boshrelease-artifacts

run:
  path: boshrelease/ci/tasks/build-final-release/task.sh

params:
  BOSHRELEASE_PRIVATE_CONFIG:
